In [4]:
%matplotlib inline
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [5]:
train_df = pd.read_csv(Path('Resources/2019loans.csv', index_col=False))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv', index_col=False))

In [6]:
pd.set_option("display.max_columns", None)
train_df.head()

# train_df.dtypes.to_dict()

Unnamed: 0   index  loan_amnt  int_rate  installment home_ownership  \
0       57107   57107    13375.0    0.1797       483.34       MORTGAGE   
1      141451  141451    21000.0    0.1308       478.68       MORTGAGE   
2      321143  321143    20000.0    0.1240       448.95       MORTGAGE   
3       11778   11778     3000.0    0.1240       100.22           RENT   
4      169382  169382    30000.0    0.1612      1056.49       MORTGAGE   

   annual_inc verification_status loan_status pymnt_plan    dti  delinq_2yrs  \
0    223000.0        Not Verified    low_risk          n  29.99          0.0   
1    123000.0     Source Verified    low_risk          n  11.26          2.0   
2    197000.0     Source Verified    low_risk          n  11.28          0.0   
3     45000.0        Not Verified    low_risk          n  18.08          0.0   
4    133000.0     Source Verified    low_risk          n  27.77          0.0   

   inq_last_6mths  open_acc  pub_rec  revol_bal  total_acc  \
0             0.0      15.0      0.0    39728.0       38.0   
1             0.0      16.0      0.0     9585.0       20.0   
2             0.0      12.0      0.0    16708.0       36.0   
3             0.0      12.0      1.0     8809.0       19.0   
4             2.0      13.0      0.0    65420.0       51.0   

  initial_list_status  out_prncp  out_prncp_inv  total_pymnt  total_pymnt_inv  \
0                   w   12804.66       12804.66       953.33           953.33   
1                   w   15152.97       15152.97     10037.02         10037.02   
2                   w   15724.23       15724.23      6971.52          6971.52   
3                   w    2930.77        2930.77        81.63            81.63   
4                   w   20778.03       20778.03     14763.99         14763.99   

   total_rec_prncp  total_rec_int  total_rec_late_fee  recoveries  \
0           570.34         382.99                 0.0         0.0   
1          5847.03        4189.99                 0.0         0.0   
2          4275.77        2695.75                 0.0         0.0   
3            69.23          12.40                 0.0         0.0   
4          9221.97        5542.02                 0.0         0.0   

   collection_recovery_fee  last_pymnt_amnt  collections_12_mths_ex_med  \
0                      0.0           483.34                         0.0   
1                      0.0           478.68                         0.0   
2                      0.0           448.95                         0.0   
3                      0.0            85.76                         1.0   
4                      0.0          1056.49                         0.0   

   policy_code application_type  acc_now_delinq  tot_coll_amt  tot_cur_bal  \
0          1.0       Individual             0.0           0.0     465790.0   
1          1.0       Individual             0.0           0.0      60769.0   
2          1.0       Individual             0.0           0.0     617946.0   
3          1.0       Individual             0.0         568.0      20761.0   
4          1.0       Individual             0.0           0.0     237839.0   

   open_acc_6m  open_act_il  open_il_12m  open_il_24m  mths_since_rcnt_il  \
0          2.0          7.0          3.0          7.0                 7.0   
1          0.0          2.0          0.0          1.0                17.0   
2          1.0          7.0          1.0          2.0                 5.0   
3          2.0          4.0          2.0          2.0                 8.0   
4          2.0          3.0          1.0          3.0                 5.0   

   total_bal_il  il_util  open_rv_12m  open_rv_24m  max_bal_bc  all_util  \
0       82290.0     70.0          1.0          1.0     24683.0      69.0   
1       18311.0     52.0          0.0          4.0      4311.0      50.0   
2       97335.0    108.0          0.0          0.0     11026.0      98.0   
3       11952.0     78.0          2.0          4.0      2409.0      49.0   
4       43636.0     74.0          1.0  

In [7]:
test_df.head()

Unnamed: 0  index  loan_amnt  int_rate  installment home_ownership  \
0       67991  67991    40000.0    0.0819       814.70       MORTGAGE   
1       25429  25429     6000.0    0.1524       208.70           RENT   
2       38496  38496     3600.0    0.1695       128.27           RENT   
3       19667  19667    20000.0    0.1524       478.33           RENT   
4       37505  37505     3600.0    0.1240       120.27           RENT   

   annual_inc verification_status loan_status pymnt_plan    dti  delinq_2yrs  \
0    140000.0        Not Verified    low_risk          n  19.75          0.0   
1     55000.0        Not Verified    low_risk          n  11.52          2.0   
2     42000.0        Not Verified    low_risk          n   6.74          0.0   
3    100000.0        Not Verified    low_risk          n  12.13          0.0   
4     50000.0        Not Verified    low_risk          n  16.08          0.0   

   inq_last_6mths  open_acc  pub_rec  revol_bal  total_acc  \
0             1.0      18.0      0.0     9471.0       45.0   
1             0.0       8.0      0.0     1280.0       12.0   
2             0.0       6.0      0.0     4757.0        6.0   
3             2.0       7.0      0.0    12731.0       21.0   
4             3.0       6.0      0.0    10413.0        6.0   

  initial_list_status  out_prncp  out_prncp_inv  total_pymnt  total_pymnt_inv  \
0                   w   33249.95       33249.95      9740.00          9740.00   
1                   w       0.00           0.00      6185.59          6185.59   
2                   w       0.00           0.00      3603.73          3603.73   
3                   w   17624.06       17624.06      4766.37          4766.37   
4                   w       0.00           0.00      3602.48          3602.48   

   total_rec_prncp  total_rec_int  total_rec_late_fee  recoveries  \
0          6750.05        2989.95                 0.0         0.0   
1          6000.00         185.59                 0.0         0.0   
2          3600.00           3.73                 0.0         0.0   
3          2375.94        2390.43                 0.0         0.0   
4          3600.00           2.48                 0.0         0.0   

   collection_recovery_fee  last_pymnt_amnt  collections_12_mths_ex_med  \
0                      0.0           814.70                         0.0   
1                      0.0          5773.27                         0.0   
2                      0.0          3607.12                         0.0   
3                      0.0           478.33                         0.0   
4                      0.0          3604.96                         0.0   

   policy_code application_type  acc_now_delinq  tot_coll_amt  tot_cur_bal  \
0          1.0       Individual             0.0           0.0     377773.0   
1          1.0       Individual             0.0           0.0      23460.0   
2          1.0       Individual             0.0           0.0      19183.0   
3          1.0       Individual             0.0           0.0      43817.0   
4          1.0       Individual             0.0           0.0      32448.0   

   open_acc_6m  open_act_il  open_il_12m  open_il_24m  mths_since_rcnt_il  \
0          1.0          6.0          1.0          2.0                 9.0   
1          1.0          1.0          1.0          1.0                 6.0   
2          0.0          3.0          0.0          0.0                40.0   
3          1.0          2.0          1.0          3.0                11.0   
4          2.0          2.0          1.0          1.0                 9.0   

   total_bal_il  il_util  open_rv_12m  open_rv_24m  max_bal_bc  all_util  \
0       61443.0     51.0          1.0          1.0      3218.0      26.0   
1       22180.0     94.0          0.0          1.0       713.0      68.0   
2       14426.0     96.0          1.0          2.0      4757.0      83.0   
3       31086.0     86.0          3.0          3.0      5917.0      78.0   
4       22035.0     88.0          2.0        

In [9]:
X_train = train_df.drop(['Unnamed: 0', 'index', 'delinq_amnt', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'tax_liens', 'recoveries', 'collection_recovery_fee', 'policy_code', 'loan_status'], axis=1)
X_test = test_df.drop(['Unnamed: 0', 'index', 'delinq_amnt', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'tax_liens', 'recoveries', 'collection_recovery_fee', 'policy_code', 'loan_status'], axis=1)

In [10]:
X_train.shape

(12180, 76)

In [11]:
X_train.dropna
X_train.shape

(12180, 76)

In [12]:
X_test.shape

(4702, 76)

In [13]:
# drop blank rows
X_test.dropna
X_test.shape

(4702, 76)

In [15]:
X_test.dtypes.to_dict()

{'loan_amnt': dtype('float64'),
 'int_rate': dtype('float64'),
 'installment': dtype('float64'),
 'home_ownership': dtype('O'),
 'annual_inc': dtype('float64'),
 'verification_status': dtype('O'),
 'pymnt_plan': dtype('O'),
 'dti': dtype('float64'),
 'delinq_2yrs': dtype('float64'),
 'inq_last_6mths': dtype('float64'),
 'open_acc': dtype('float64'),
 'pub_rec': dtype('float64'),
 'revol_bal': dtype('float64'),
 'total_acc': dtype('float64'),
 'initial_list_status': dtype('O'),
 'out_prncp': dtype('float64'),
 'out_prncp_inv': dtype('float64'),
 'total_pymnt': dtype('float64'),
 'total_pymnt_inv': dtype('float64'),
 'total_rec_prncp': dtype('float64'),
 'total_rec_int': dtype('float64'),
 'total_rec_late_fee': dtype('float64'),
 'last_pymnt_amnt': dtype('float64'),
 'collections_12_mths_ex_med': dtype('float64'),
 'application_type': dtype('O'),
 'acc_now_delinq': dtype('float64'),
 'tot_coll_amt': dtype('float64'),
 'tot_cur_bal': dtype('float64'),
 'open_acc_6m': dtype('float64'),
 'o

In [16]:
y_train = train_df.loan_status.values
y_test = test_df.loan_status.values

In [18]:
X_train.describe()

loan_amnt      int_rate   installment    annual_inc           dti  \
count  12180.000000  12180.000000  12180.000000  1.218000e+04  12180.000000   
mean   17399.579228      0.140899    509.150241  8.989320e+04     22.589516   
std    10238.160884      0.052679    294.617726  1.684370e+05     23.903223   
min     1000.000000      0.060000     30.890000  5.000000e+02      0.100000   
25%    10000.000000      0.103300    286.902500  5.000000e+04     14.500000   
50%    15000.000000      0.130800    438.530000  7.300000e+04     20.375000   
75%    25000.000000      0.177400    682.230000  1.035850e+05     27.290000   
max    40000.000000      0.308400   1671.880000  9.682505e+06    999.000000   

        delinq_2yrs  inq_last_6mths      open_acc      pub_rec      revol_bal  \
count  12180.000000    12180.000000  12180.000000  12180.00000   12180.000000   
mean       0.256979        0.566502     12.680296      0.11601   17593.681773   
std        0.803027        0.814674      6.154663      0.32960   22602.217861   
min        0.000000        0.000000      2.000000      0.00000       0.000000   
25%        0.000000        0.000000      8.000000      0.00000    6306.000000   
50%        0.000000        0.000000     11.000000      0.00000   11971.500000   
75%        0.000000        1.000000     16.000000      0.00000   21500.250000   
max       15.000000        5.000000     65.000000      4.00000  506260.000000   

          total_acc     out_prncp  out_prncp_inv   total_pymnt  \
count  12180.000000  12180.000000   12180.000000  12180.000000   
mean      24.398522  13431.612526   13430.333733   6382.471844   
std       12.555693   8785.098800    8785.817001   4963.811515   
min        3.000000      0.000000       0.000000      0.000000   
25%       15.000000   6379.132500    6379.132500   2696.870000   
50%       22.000000  11562.660000   11562.660000   5381.485000   
75%       31.000000  19080.782500   19080.782500   8880.985000   
max      117.000000  40000.000000   40000.000000  41994.490000   

       total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  \
count     12180.000000     12180.000000   12180.000000        12180.000000   
mean       6381.744212      3967.966703    2412.603877            1.901265   
std        4963.738304      3676.345410    2096.113616           12.593238   
min           0.000000         0.000000       0.000000            0.000000   
25%        2696.757500      1461.777500     778.850000            0.000000   
50%        5381.250000      3022.285000    1877.930000            0.000000   
75%        8880.710000      5284.890000    3474.925000            0.000000   
max       41994.490000     35000.000000   15963.070000          337.350000   

       last_pymnt_amnt  collections_12_mths_ex_med  acc_now_delinq  \
count     12180.000000                12180.000000    12180.000000   
mean        438.597455                    0.020115        0.000082   
std         829.311869                    0.151103        0.009061   
min       -1260.780000                    0.000000        0.000000   
25%         139.140000                    0.000000        0.000000   
50%         337.330000                    0.000000        0.000000   
75%         591.555000                    0.000000        0.000000   
max       28090.390000                    3.000000        1.000000   

       tot_coll_amt   tot_cur_bal   open_acc_6m   open_act_il   open_il_12m  \
count  12180.000000  1.218000e+04  12180.000000  12180.000000  12180.000000   
mean     185.009031  1.555372e+05      1.051970      3.349261      0.874713   
std     1324.251148  1.717668e+05      1.207107      3.095097      0.992740   
min        0.000000  1.755000e+03      0.000000      0.000000      0.000000   
25%        0.000000  3.407175e+04      0.000000      2.000000      0.000000   
50%        0.000000  8.502650e+04      1.000000      2.000000      1.000000   
75%        0.000000  2.317975e+05      2.000000      4.000000      1.000000   
max    

In [19]:
# Note: payment plan column for all rows indiates "n" for tain and test, the column has dropped out 
# Note: Debt settlement flag for the test file has dropped and needs to be re-added to the test_dummy file for alignment with the train df. 

X_train = pd.get_dummies(X_train, columns=['home_ownership', 'verification_status', 'pymnt_plan', 'initial_list_status', 'application_type', 'hardship_flag', 'debt_settlement_flag'],drop_first=True, dtype=float)
X_test = pd.get_dummies(X_test, columns=['home_ownership', 'verification_status', 'pymnt_plan', 'initial_list_status', 'application_type', 'hardship_flag', 'debt_settlement_flag'],drop_first=True, dtype=float)

In [20]:
# Missing column "debt settlement flag" on x_test file
X_train.dtypes.to_dict()
X_train.shape

(12180, 78)

In [21]:
# Missing column "debt settlement flag" on x_test file
X_test['debt_settlement_flag_Y'] = test_df.debt_settlement_flag.map({'N':0}).astype(float)
X_test.shape

(4702, 78)

In [22]:
# Categorical Data to Numeric Y label train and test
y_train = LabelEncoder().fit_transform(y_train).astype(float)
y_test = LabelEncoder().fit_transform(y_test).astype(float)

In [23]:
# model.coef_
# X_train.columns
X_train.shape
y_train

array([1., 1., 1., ..., 0., 0., 0.])

In [24]:
# variables used for unscaled Logistic Regression and unscaled Random Forest
X_train_log_reg = pd.DataFrame(X_train)
X_test_log_reg = pd.DataFrame(X_test)
X_train_ran_forest = pd.DataFrame(X_train)
X_test_ran_forest = pd.DataFrame(X_test)

In [25]:
model_params = {
    'random_forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [30, 40, 50, 60, 70]
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [0.5, 1, 1.5]
        }
    }
}

In [26]:
from sklearn.model_selection import GridSearchCV

scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(X_train, y_train)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

C:\Users\mjenk\Anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


In [27]:
scores_df = pd.DataFrame(scores,columns=['model', 'best_score', 'best_params'])
scores_df

model  best_score           best_params
0        random_forest    0.757800  {'n_estimators': 70}
1  logistic_regression    0.699589            {'C': 1.5}

In [28]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train_log_reg, y_train)

C:\Users\mjenk\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [29]:
print(f"Training Data Score: {model.score(X_train_log_reg, y_train)}")
print(f"Testing Score: {model.score(X_test_log_reg, y_test)}")

Training Data Score: 0.6499178981937602
Testing Score: 0.5168013611229264


In [30]:
print(classification_report(y_test,model.predict(X_test_log_reg), target_names=['high_risk', 'low_risk']))

              precision    recall  f1-score   support

   high_risk       0.53      0.30      0.38      2351
    low_risk       0.51      0.73      0.60      2351

    accuracy                           0.52      4702
   macro avg       0.52      0.52      0.49      4702
weighted avg       0.52      0.52      0.49      4702



In [31]:
# confusion matrix
y_true = y_test
y_pred = model.predict(X_test_log_reg)
confusion_matrix(y_true, y_pred, labels=[1,0])

array([[1719,  632],
       [1640,  711]], dtype=int64)

In [32]:
accuracy_score(y_true,y_pred)

0.5168013611229264

In [33]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(random_state=1, n_estimators=70).fit(X_train_ran_forest, y_train)
print(classification_report(y_test,classifier.predict(X_test_ran_forest), target_names=['high_risk', 'low_risk']))

              precision    recall  f1-score   support

   high_risk       0.59      0.81      0.68      2351
    low_risk       0.70      0.44      0.54      2351

    accuracy                           0.63      4702
   macro avg       0.65      0.63      0.61      4702
weighted avg       0.65      0.63      0.61      4702



In [34]:
print(f"Training Data Score: {classifier.score(X_train_ran_forest, y_train)}")
print(f"Testing Score: {classifier.score(X_test_ran_forest, y_test)}")

Training Data Score: 1.0
Testing Score: 0.6261165461505742


In [35]:
# confusion matrix
y_true = y_test
y_pred = classifier.predict(X_test)
confusion_matrix(y_true, y_pred, labels=[1,0])

array([[1045, 1306],
       [ 452, 1899]], dtype=int64)

In [36]:
accuracy_score(y_true,y_pred)

0.6261165461505742

In [37]:
# Note: StandardScaler does not work well with outliers
X_scaler = StandardScaler().fit(X_train)
X_scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [38]:
from sklearn.linear_model import LogisticRegression
model_scaled = LogisticRegression()
model_scaled.fit(X_train_scaled, y_train)

C:\Users\mjenk\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [39]:
print(f"Training Data Score: {model_scaled.score(X_train_scaled, y_train)}")
print(f"Testing Score: {model_scaled.score(X_test_scaled, y_test)}")

Training Data Score: 0.7082922824302135
Testing Score: 0.7686091025095704


In [40]:
print(classification_report(y_test,model_scaled.predict(X_test_scaled), target_names=['high_risk', 'low_risk']))

              precision    recall  f1-score   support

   high_risk       0.77      0.76      0.77      2351
    low_risk       0.76      0.78      0.77      2351

    accuracy                           0.77      4702
   macro avg       0.77      0.77      0.77      4702
weighted avg       0.77      0.77      0.77      4702



In [41]:
# confusion matrix
y_true = y_test
y_pred = model_scaled.predict(X_test_scaled)
confusion_matrix(y_true, y_pred, labels=[1,0])

array([[1825,  526],
       [ 562, 1789]], dtype=int64)

In [42]:
accuracy_score(y_true,y_pred)

0.7686091025095704

In [43]:
from sklearn.ensemble import RandomForestClassifier
classifier_scaled = RandomForestClassifier(random_state=1, n_estimators=70).fit(X_train_scaled, y_train)
print(classification_report(y_test,classifier_scaled.predict(X_test_scaled), target_names=['high_risk', 'low_risk']))

              precision    recall  f1-score   support

   high_risk       0.59      0.81      0.69      2351
    low_risk       0.70      0.44      0.54      2351

    accuracy                           0.63      4702
   macro avg       0.65      0.63      0.61      4702
weighted avg       0.65      0.63      0.61      4702



In [44]:
print(f"Training Data Score: {classifier_scaled.score(X_train_scaled, y_train)}")
print(f"Testing Score: {classifier_scaled.score(X_test_scaled, y_test)}")

Training Data Score: 1.0
Testing Score: 0.6271799234368354


In [45]:
# confusion matrix
y_true = y_test
y_pred = classifier_scaled.predict(X_test_scaled)
confusion_matrix(y_true, y_pred, labels=[1,0])

array([[1042, 1309],
       [ 444, 1907]], dtype=int64)

In [47]:
accuracy_score(y_true,y_pred)

0.6271799234368354

In [ ]:
# Key Takeaways
# Scaling appears to have no impact on the Random Logistic model scoring.
# A very significant improvement in the Logistical Regression score from 52% to 77% if scalling the loan data prior to fitting the model.
# Overall, Logistic Regression on the scaled data model provides the best results at 77% on predicting high or low risk loans.
# Logistic Regression outperformed Rain Forest methodsS